const listLineItems = {
  id: "cs_test_a1Z0TRFd6cV50qCBZRAMahSdmYQWuyfnqj8rFHROtDuAcFN87r4LLWtmyS",
  object: "checkout.session",
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 180000,
  amount_total: 180000,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: "required",
  cancel_url: "http://localhost:3000/order?canceled=1",
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  created: 1707051372,
  currency: "inr",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: null,
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: "Gandhinagar",
      country: "IN",
      line1: "gandhi",
      line2: "sector 27 samarapan circle home no.861",
      postal_code: "382027",
      state: "GJ",
    },
    email: "hardikbhammar88@gmail.com",
    name: "Hardik Bhammar",
    phone: "+917046478268",
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1707137772,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: null,
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: {
    images:
      '["https://res.cloudinary.com/dctww9bm8/image/upload/v1706770969/Image_upload/realme-6-rbs0605in-original-imafpmft8nkyapha_fk6nbm.webp"]',
    productId: "9b0b688e-2076-4b09-8e70-564f9d51d7ef",
    email: "hardikbhammar88@gmail.com",
    orderId: "9d329a92-5584-40f8-b320-3687c1391810",
    productName: "Realme  6",
  },
  mode: "payment",
  payment_intent: "pi_3Og5FOSCNlaf5syu1DC0lsCg",
  payment_link: null,
  payment_method_collection: "if_required",
  payment_method_configuration_details: null,
  payment_method_options: {},
  payment_method_types: ["card"],
  payment_status: "paid",
  phone_number_collection: { enabled: true },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: { allowed_countries: ["GB", "US", "IN"] },
  shipping_cost: null,
  shipping_details: {
    address: {
      city: "Gandhinagar",
      country: "IN",
      line1: "gandhi",
      line2: "sector 27 samarapan circle home no.861",
      postal_code: "382027",
      state: "GJ",
    },
    name: "Hardik Bhammar",
  },
  shipping_options: [],
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url: "http://localhost:3000/order?success=1",
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: "hosted",
  url: null,
};
